// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQXgps71nOKo_Y-m96UrmP97l1IbuYvoE',
    appId: '1:695100833766:web:6f4b03d749a2d8daa96027',
    messagingSenderId: '695100833766',
    projectId: 'testelogin-6c56e',
    authDomain: 'testelogin-6c56e.firebaseapp.com',
    storageBucket: 'testelogin-6c56e.appspot.com',
    measurementId: 'G-0LWBW4LK2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAewJ4Lo3rzXrZE9PtTykhejjvKrjwxDk',
    appId: '1:695100833766:android:60bf9fb09fafcaada96027',
    messagingSenderId: '695100833766',
    projectId: 'testelogin-6c56e',
    storageBucket: 'testelogin-6c56e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJl-NG5eWGEEbaobQ3KfeATT0iYWkAM9g',
    appId: '1:695100833766:ios:08a5ffe5b1bd36c1a96027',
    messagingSenderId: '695100833766',
    projectId: 'testelogin-6c56e',
    storageBucket: 'testelogin-6c56e.appspot.com',
    iosClientId: '695100833766-3q85p8apnnjab5pafvkv49obso4dqdog.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoPi1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJl-NG5eWGEEbaobQ3KfeATT0iYWkAM9g',
    appId: '1:695100833766:ios:08a5ffe5b1bd36c1a96027',
    messagingSenderId: '695100833766',
    projectId: 'testelogin-6c56e',
    storageBucket: 'testelogin-6c56e.appspot.com',
    iosClientId: '695100833766-3q85p8apnnjab5pafvkv49obso4dqdog.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoPi1',
  );
}
